source 'https://rubygems.org'

gem 'jekyll', '3.7.3'
gem 'jekyll-paginate'
gem 'jekyll-assets'
gem 'html-proofer'
gem 'redcarpet'
gem 's3_website'
gem 'jekyll-extlinks'
gem 'citeproc-ruby'
gem 'bibtex-ruby'
gem 'csl-styles'
gem 'unicode_utils'