name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm install

    # Inject Google Analytics ID
    - run: sed -i '' 's/UA-XXXXXXXX-X/'"${secrets.GOOGLE_ANALYTICS_ID}"'/g' src/site/_assets/js/analytics.js

    # Build Eleventy site
    - run: npm run build

    # Deploy the site to AWS S3 + CloudFront (if non-staging)
    - name: Deploy
      uses: docker://justinharringa/s3_website:master
      with:
        args: 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}