---
name: Lint Code Base

on:
  push:
  pull_request:

jobs:
  linting:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint_commands: ["lint:css", "lint:js"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: ${{ matrix.lint_commands }}
        run: npm run ${{ matrix.lint_commands }}
