markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:month/:title/
safe: false
exclude: ['s3_website.yml', 'Jenkinsfile', 'README.md', 'tmp/', 'Gemfile', 'Gemfile.lock']
paginate: 5

plugins:
- jekyll-paginate
- jekyll-assets
- jekyll-extlinks

collections:
  videos:
    output: true
    permalink: /videos/:path/

  courses:
    output: true
    permalink: /courses/:path/

excerpt_separator: <!--more-->

assets:
  # compression: true
  sources:
    - "_assets/css"
    - "_assets/js"

redcarpet:
    extensions: ["footnotes"]

extlinks:
  attributes: {target: _blank, class: 'external', data-no-instant: 'data-no-instant'}
  rel_exclude: ['savjee.be']